language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 90f68d9a1fff8c9774864d63fb554a052a513919
  local_dir: dist
  on:
    branch: master